// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBVSgdW3Sd5eXOgU4Wmym348_ZesCadsc',
    appId: '1:50419247622:web:8e6ed66471efa1d0af3187',
    messagingSenderId: '50419247622',
    projectId: 'sccapwl-9fc3d',
    authDomain: 'sccapwl-9fc3d.firebaseapp.com',
    storageBucket: 'sccapwl-9fc3d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXL2G9joNwa-60AUsOgEPEuX3hH_KYhto',
    appId: '1:50419247622:android:4365fae12fea70c0af3187',
    messagingSenderId: '50419247622',
    projectId: 'sccapwl-9fc3d',
    storageBucket: 'sccapwl-9fc3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8-nOoPcINyW5a_BlC7YveFKPvfuuQwek',
    appId: '1:50419247622:ios:0ef2bcca3b8202c0af3187',
    messagingSenderId: '50419247622',
    projectId: 'sccapwl-9fc3d',
    storageBucket: 'sccapwl-9fc3d.appspot.com',
    iosBundleId: 'com.example.sccapwlMovil',
  );
}
