// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhQat_ThJsU670svUsyTSKcp923OZsai8',
    appId: '1:721746651058:web:4cf082d29f9c2985f9e6ab',
    messagingSenderId: '721746651058',
    projectId: 'waterlight-918c1',
    authDomain: 'waterlight-918c1.firebaseapp.com',
    storageBucket: 'waterlight-918c1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA51V-Y4fnmgKVlVJ5lU1irbjY2eSd-tvs',
    appId: '1:721746651058:android:bffaf49d7ee3ba7bf9e6ab',
    messagingSenderId: '721746651058',
    projectId: 'waterlight-918c1',
    storageBucket: 'waterlight-918c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_YS2fiVudJHPKU0HJzzpmKZoZU4q77KQ',
    appId: '1:721746651058:ios:6fc0442f3535cbe4f9e6ab',
    messagingSenderId: '721746651058',
    projectId: 'waterlight-918c1',
    storageBucket: 'waterlight-918c1.appspot.com',
    iosBundleId: 'com.example.sccapwlMovil',
  );
}
